name: nlp
services:
  gpt:
    image: ghcr.io/open-webui/open-webui:ollama
    restart: unless-stopped
    environment:
      WEBUI_URL: https://zdl-gpu01.bbaw.de
      ENABLE_SIGNUP: true
      WEBUI_NAME: ZDL LLMs
      ENABLE_REALTIME_CHAT_SAVE: true
      ENABLE_OPENAI_API: false
      ENABLE_CODE_EXECUTION: false
      ENABLE_CODE_INTERPRETER: false
    volumes:
      - gpt:/app/backend/data
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  http:
    image: caddy
    restart: unless-stopped
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    volumes:
      - caddy:/data
    ports:
        - '80:80'
        - '443:443'
        - '443:443/udp'
    tty: true
volumes:
  gpt:
  ollama:
  caddy:
configs:
  caddy_config:
    content: >-
      zdl-gpu01.bbaw.de {
          tls internal
          reverse_proxy gpt:8080 {
              header_up Host {host}
              header_up X-Real-IP {remote}
              header_up X-Forwarded-For {remote}
              header_up X-Forwarded-Proto {scheme}

              # Health checks
              health_uri /health
              health_interval 30s
              health_timeout 10s
              health_status 200

              # Timeouts
              transport http {
                  keepalive 30s
                  keepalive_idle_conns 10
              }
          }
      }
