services:
  index:
    image: zdl/index
    build:
      context: docker/index
    volumes:
      - index:/var/solr
    ports:
      - "8983:8983"
    environment:
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
volumes:
  index:
