#!/usr/bin/env python
from os import execlp
from pathlib import Path

project_dir = Path(__file__).parent.parent
ddc_corpora_dir = project_dir / "data" / "ddc-corpora"

ddc_corpora_dir.mkdir(parents=True, exist_ok=True)

execlp(
    "sshfs",
    "sshfs",
    "nlp@ddc-build.bbaw.de:/home/ddc-dstar/dstar/sources",
    str(ddc_corpora_dir),
    "-o",
    "ro",
)
